name: Slither Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Slither and Solc
        run: |
          sudo apt-get update
          sudo apt-get install -y solc
          pip install slither-analyzer

      - name: Run Slither Analysis and Generate Report
        run: |
          slither ./contracts --json slither-report.json

