name: Slither Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y solc
          pip install slither-analyzer

      - name: Run Slither Analysis
        run: |
          slither ./contracts --exclude low --exclude optimization || exit 1
